language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3 BAP=rfclint/linux
        - os: linux
          python: 3.5
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3 BAP=rfclint/linux
        - os: linux
          python: 3.6
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3 BAP=rfclint/linux
        - os: linux
          python: 3.7
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3 BAP=rfclint/linux
          dist: xenial
          sudo: true
        - os: linux
          python: pypy3
          env: PYTHON=python PIP=pip BAP=rfclint/linux
        - os: osx
          language: generic
          env: TOXENV=py27 PYTHON=python2 PIP=pip2 BAP=rfclint/macos
        - os: osx
          language: generic
          env: TOXENV=py36 PYTHON=python3 PIP=pip3 BAP=rfclint/macos

addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - hunspell

install:
    - ./install.sh

script:
  - export PATH=$PATH:${HOME}/build/ietf-tools/RfcEditor/$BAP
  - pwd
  - mkdir dist
  - python --version
  - cd rfctools_common && $PYTHON setup.py --quiet install
  - pwd
  - cd ../rfclint && $PYTHON setup.py --quiet install
  - cd ../svgcheck && $PYTHON setup.py --quiet install
  - cd ../xmldiff && $PYTHON setup.py --quiet install
  - $PYTHON setup.py --quiet bdist_wheel

  - cd ..
  - $PIP install -r requirements.txt
  - cd rfctools_common/rfctools_common && $PYTHON test.py
  - cd ../..
  - cd svgcheck/svgcheck && $PYTHON test.py
  - cd ../..
  - cd rfclint/rfclint && $PYTHON test.py
  - cd ../..
  - cd xmldiff/Test && $PYTHON test.py
  - cd ../..
  - pwd
  - ls dist
