language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - PYTHONPATH="$PWD"/Com-AugustCellars

install:
  - pip install -r requirements.txt

script:
  - pwd
  - python common/test.py
 