language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
        - os: linux
          python: 3.6
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
        - os: linux
          python: 3.4
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
        - os: linux
          python: 3.5
          env: PYTHON=python PIP=pip  MALLOC_CHECK_=3
        - os: linux
          python: pypy3
          env: PYTHON=python PIP=pip
        - os: osx
          language: generic
          env: TOXENV=py27 PYTHON=python2 PIP=pip2
        - os: osx
          language: generic
          env: TOXENV=py36 PYTHON=python3 PIP=pip3

addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - hunspell

install:
    - ./install.sh

script:
  - $PIP install -r requirements.txt
  - pwd
  - mkdir dist
  - python --version
  - cd rfctools_common && $PYTHON setup.py --quiet install
  - pwd
  - cd rfctools_common && $PYTHON test.py
  - cd ../../svgcheck
  - $PYTHON setup.py --quiet install
  - cd svgcheck
  - $PYTHON test.py
  - cd ../../rfclint
  - $PYTHON setup.py --quiet install
  - cd rfclint
  - $PYTHON test.py
  - cd ../../xmldiff
  - $PYTHON setup.py --quiet install
  - $PYTHON setup.py --quiet bdist_wheel
  - cp dist/* ../dist
  - cd Test
  - $PYTHON test.py
  - ../..
  - ls dist

before_deploy:
  openssl aes-256-cbc -K $encrypted_b97c0a903367_key -iv $encrypted_b97c0a903367_iv -in deploy_key.enc -out deploy_key -d
 
deploy:
  provider: releases
  api_key: "GITHUB AUTH TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    